### ISSUE TITLE
Item Creation Date Format

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#177]
Hey guys, 
While creating item, date format that is required for API call seems pretty long and unnecessary, 
What about changing it to YYYY-MM-DD?

reference: https://www.w3.org/TR/NOTE-datetime

**Comment by mehmetgulsen** [comment]
We are trying to figure that one out as well, mostly about the use of timezones. When we use the timezone features of django, it makes datetimes with values like "2017-11-24T08:47:51.091000Z". When we don't use it, it makes them like "2017-11-25 08:28:24.368000". Please focus on other stuff while we figure this out.

**Comment by hakansirin** [comment]
Heritage item has two time related fields which both are DataTime fields for now.
First one is creation_date and I believe most suitable format for it is DateTime field which is also the current format. It is not taken from the user and automatically generated at the backend.

For the other event_date field, I agree that DateTime for it is a little bit of a overkill and it doesn't makes sense to ask the user exact millisecond of the item's event date. One possible solution for now might be only ask for the date and send us the JSON field as for example 
"event_date": "2017-10-25T00:00:00Z"

Event_date format is likely to change in the future anyways, because it fails to describe heritage items that are specific to a given period of time. So I will take this matter in to the next weekly meeting's agenda. Feel free to join us.

**Comment by hakansirin** [comment]
I can still add extra two fields to the returning jsons for heritage items as short_event_date and short_creation_date in the format you asked or any other format if you would like to.  How does it sound?

**Comment by mehmetgulsen** [comment]
I have just tested it. You just need to send the event date like "2017-11-25 12:27:00". Our model converts it to our system with no problems. What you will get for event date when you make a query for that heritage is "2017-10-10T10:26:30+03:00". I don't know how android works so you might need to parse it.

**Comment by mehmetgulsen** [comment]
Pull request is here: #181

**Comment by hakansirin** [comment]
This pull request has no relations to the issue that Sefa stated. And closing this issue referencing that only causes confusion.  
Plus, I am still waiting a response from Sefa to my offered temporary solution.

**Comment by mehmetgulsen** [comment]
I closed it because I've told him to use "YYYY-MM-DD HH:MM:SS". We have always been using datetime fields instead of seperate date and time fields. As Sefa himself said in issue #172  , refactoring an API, especially when there are no problems, is not a good idea. If we do it for just heritages, the same problems Sefa was complaining about will happen to the Frontend team, as well as create an inconsistency across different models as we are using datetime field for them.

If it is working, don't fix it.

**Comment by mehmetsefa2644** [comment]
@mehmetgulsen is right, it is working, so we shall go on using this format, closing.
