### ISSUE TITLE
Search performance is great but we need a lower bound

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#230]
To stop the system return seemingly unrelated items for search, it might be a good idea to add a score lower bound.
It`s up to your judgement how big the lower bound should be.

**Comment by mehmetgulsen** [comment]
These are the score coefficents for matches as of now:
Title: 5 points
Description: 3 points
Location: 3 points
Tag: 5 points
Tag related stuff: 1 points for each occurence (is not taken into account if the tag itself matches)

I think I will be setting the limit as 3 points. It should filter out some unnecessary stuff that appears due to some tag related stuff matches. If you have another opinion, feel free to let me know.

**Comment by mehmetgulsen** [comment]
Done. You can look at the code at #231 if you wish.

Let me know if you think it is still not good enough. I can simply increase the lower bound and/or make it scale up according to the number of words the user inputs as a search query.
